let background=document.createElement("div")
background.classList.add("background")
document.body.appendChild(background)
let background1=document.createElement("div")
background1.classList.add("background1")
background.appendChild(background1)
let vector=document.createElement("div")
vector.classList.add("vector")
background1.appendChild(vector)